- README.md
- official/fixtures/client-library-fixtures.json
Adds a reusable JSON blob of fixture data we'll start using in our client libraries. Each library will submodule this new `examples` repo to get examples to live alongside the code as well as allowing us to reuse test data with a single source of truth.
> feat: adds fixtures to repo

- official/fixtures/client-library-fixtures.json
Languages like Golang can't deserialize the min/max datetime of a Pickup unless it is fully qualified. We fix this here.
> fix: fully qualify pickup min/max datetimes

- Makefile
- Fixes various installation targets that previously could not be run or would throw errors.
- Fixes the Java lint target which previously silently failed stating it could not find Java files
> fix: Makefile install and lint targets

- official/docs/curl/current/shipments/label.sh
The `shipments/:id/label` endpoint is actually a GET.
A POST gives us:
```
{
"error": {
"code": "NOT_FOUND",
"message": "The requested resource could not be found.",
"errors": []
}
}
```
A GET gives a successful 200.
See https://github.com/EasyPost/easypost-python/blob/master/easypost/shipment.py#L84 for how our Python client library does a GET not a POST.
> Fix shipments/:id/label cURL request

- .github/workflows/ci.yml
- test/ensure-current-dirs-exist.sh
Adds a script that runs on CI to ensure we don't break our folder structure for snippet files.
Tested by renaming some to `currents` and it failed and output the errors.
> tests: adds a test to ensure we don't break our folder structure for document snippets

- official/fixtures/client-library-fixtures.json
Updates the test credit card to a new test number provided by Stripe.
> chore: update test credit card fixture

- official/fixtures/client-library-fixtures.json
Apparently we went down this road before and this doesn't work, even though I definitely had it work this morning, Stripe's API is complaining we are sending test credit card details to their prod endpoint which is valid since we don't hit the test one. We're trying to test in production which isn't super possible except by using our fake prod card as we were before.
This reverts commit 873ab73e2b0890c498dba3ecf0eb591c5b398dea.
> Revert "chore: update test credit card fixture"

- official/guides/sms-tracking-tutorial/step3a.sh
During our convos of versioning, we discussed what the canonical URL for our endpoint is. Searched for any incorrect references and only found one for what we are responsible for (this is still valid but will be turned off in the future, fixing now).
> fix: easypost url for sms guide

- official/docs/php/v5/carrier-accounts/update.php
Corrects the syntax of the PHP update carrier account example for v5
> fix: php carrier account update v5 example

- official/docs/csharp/current/smartrate/retrieve-estimated-delivery-date.cs
- official/docs/curl/current/smartrate/retrieve-estimated-delivery-date.sh
- official/docs/golang/current/smartrate/retrieve-estimated-delivery-date.go
- official/docs/java/current/smartrate/retrieve-estimated-delivery-date.java
- official/docs/node/current/smartrate/retrieve-estimated-delivery-date.js
- official/docs/php/current/smartrate/retrieve-estimated-delivery-date.php
- official/docs/python/current/smartrate/retrieve-estimated-delivery-date.py
- official/docs/responses/smartrate/smartrate-retrieve-estimated-delivery-date.json
- official/docs/ruby/current/smartrate/retrieve-estimated-delivery-date.rb
Adds `retrieve-estimated-delivery-date` placeholders. Response and curl are here for now, other languages will be added in a follow-up PR once we've added them to each lib.
> feat: adds retrieve-estimated-delivery-date placeholders

- official/docs/curl/current/rates/retrieve-stateless.sh
Our API is throwing `Malformed request` because of the extra comma at the end of `email`
> remove unnecessary comma in curl for stateless rate

- official/guides/rate-limiting/retry_and_backoff.py
I played around with our retry example and found a param that was deprecated and renamed and a line that isn't even used. Fixed
> fix: retry example

- go.mod
- go.sum
- official/docs/csharp/current/api-keys/retrieve.cs
- official/docs/golang/current/api-keys/retrieve.go
- official/docs/java/current/api-keys/retrieve.java
- official/docs/node/current/api-keys/retrieve.js
- official/docs/php/current/api-keys/retrieve.php
- official/docs/python/current/api-keys/retrieve.py
- official/docs/ruby/current/api-keys/retrieve.rb
Now that the functions are available for a next release on C# and Node libraries, add examples to get API Keys for child users for these. It also add missing example for Java library, which already has that functionality.
> Add missing API key retrieval examples

- official/guides/errors-guide/csharp/catch-error.cs
- official/guides/errors-guide/golang/catch-error.go
- official/guides/errors-guide/java/catch-error.java
- official/guides/errors-guide/node/catch-error.js
- official/guides/errors-guide/php/catch-error.php
- official/guides/errors-guide/python/catch-error.py
- official/guides/errors-guide/ruby/catch-error.rb
The examples for catching errors do not reflect the most recent releases of the libraries where we completely overhauled error handling. This PR updates the syntax to match.
> fix: catch error examples

- style_guides/csharp/.editorconfig
In .NET 8.0, it's encouraged to use [`CompositeFormat`](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1863) (pre-formatted string). This does not exist in older .NET versions, so we will globally suppress this for now.
> [chore] Ignore pre-formatted string suggestion in .NET 8.0

- official/fixtures/client-library-fixtures.json
Use a better "incorrect address" fixture for unit tests dealing with invalid addresses.
I have confirmed that using this fixture will cause the API to produce an "Address not found" verification error.
> [chore] Update "incorrect address" fixture

- README.md
- community/docs/http_files/README.md
- community/docs/http_files/addresses.http
- community/docs/http_files/api-keys.http
- community/docs/http_files/batches.http
- community/docs/http_files/billing.http
- community/docs/http_files/brands.http
- community/docs/http_files/carrier-accounts.http
- community/docs/http_files/carrier-metadata.http
- community/docs/http_files/carrier-types.http
- community/docs/http_files/customs-infos.http
- community/docs/http_files/customs-items.http
- community/docs/http_files/endshippers.http
- community/docs/http_files/insurance.http
- community/docs/http_files/orders.http
- community/docs/http_files/parcels.http
- community/docs/http_files/pickups.http
- community/docs/http_files/rates.http
- community/docs/http_files/referral-customers.http
- community/docs/http_files/refunds.http
- community/docs/http_files/reports.http
- community/docs/http_files/scanforms.http
- community/docs/http_files/shipments.http
- community/docs/http_files/smartrate.http
- community/docs/http_files/trackers.http
- community/docs/http_files/users.http
- community/docs/http_files/webhooks.http
Adds `.http` files for HTTP snippets for each endpoint of the API and example calls.
Developers can use these files in tandem with the [REST Client plugin](https://marketplace.visualstudio.com/items?itemName=humao.rest-client) in VSCode or the [HTTP Client plugin](https://www.jetbrains.com/help/idea/2023.3/http-client-in-product-code-editor.html) in JetBrains IDEs, where they can be run one-off, chained as request-response pairs, or exported as cURL requests or other supported languages.
This is placed in the "community" section, as it is not officially supported or maintained by EasyPost.
> [feat] Add `.http` files for API call references

- official/docs/node/current/billing/fund.js
- official/docs/node/v5/billing/fund.js
- official/docs/node/v6/billing/fund.js
The node examples have the incorrect `fund` reference that was changed prior to release to `fundWallet`. This fixes those.
> fix: fundWallet reference for Node docs

- official/docs/curl/current/addresses/list.sh
- official/docs/curl/current/batches/list.sh
- official/docs/curl/current/billing/create-ep-credit-card.sh
- official/docs/curl/current/billing/create-referral-token.sh
- official/docs/curl/current/child-users/list.sh
- official/docs/curl/current/endshipper/list.sh
- official/docs/curl/current/events/list.sh
- official/docs/curl/current/insurance/list.sh
- official/docs/curl/current/pagination/get-next-page.sh
- official/docs/curl/current/pickups/list.sh
- official/docs/curl/current/rates/retrieve-stateless.sh
- official/docs/curl/current/referral-customers/add-payment-method-with-bank-account.sh
- official/docs/curl/current/referral-customers/add-payment-method-with-credit-card.sh
- official/docs/curl/current/referral-customers/create.sh
- official/docs/curl/current/referral-customers/list.sh
- official/docs/curl/current/referral-customers/refund-by-amount.sh
- official/docs/curl/current/referral-customers/refund-by-payment-log.sh
- official/docs/curl/current/referral-customers/update.sh
- official/docs/curl/current/refunds/list.sh
- official/docs/curl/current/reports/list.sh
- official/docs/curl/current/scan-form/list.sh
- official/docs/curl/current/shipments/list.sh
- official/docs/curl/current/trackers/list.sh
Found various inconsistencies of quoting in our curl URLs, they should only be quoted when we have URL params
> fix: curl quoting of URLs

- style_guides/node/.eslintrc
- style_guides/node/.prettierignore
Unless I am missing something, these files are only used in the easypost/node client library, and they are safe to remove. I tested removing them, and the lint function still works.
Also removed the package.json, Readme, and other json-type files from prettierignore, since it would still be nice to be able to format those files when making changes.
> Remove Webpack and Babel dependencies in ESLint

- official/fixtures/client-library-fixtures.json
"First" is no more, need to use "GroundAdvantage" in unit tests
> [chore] Replace USPS service level name

- official/guides/errors-guide/golang/catch-error.go
Per the docs, this new method of error comparison is preferred, let's follow best practice: https://pkg.go.dev/errors (bottom)
> fix: use preferred method of error comparison for go guide example

- official/tools/build_create_carrier_curl_requests/README.md
- official/tools/build_create_carrier_curl_requests/build_curls.py
Porting this tool over from https://github.com/Justintime50/easypost-tools/blob/main/src/tools/python/build_carrier_curl_requests.py to make it official since we've been using it officially for a bit now.
> feat: adds build carrier curls tool

- community/golang/concurrent_insurance_buy/concurrent_insurance_buy.go
Provides more guardrails like checking for data existence, header validity, and clarifying verbage
> fix: provide more guardrails for bulkins tool

- official/docs/csharp/current/orders/one-call-buy.cs
- official/docs/csharp/current/pickups/create.cs
- official/docs/csharp/v5/orders/one-call-buy.cs
- official/docs/csharp/v5/pickups/create.cs
Existing examples for .NET are incorrect regarding how to include carrier accounts in Order/Pickup creation calls.
> [fix] Fix/clarify carrier account parameter usage for Order and Pickup creation calls in .NET

- official/docs/curl/current/webhooks/create.sh
- official/docs/curl/current/webhooks/update.sh
- official/fixtures/client-library-fixtures.json
Adds a simple fixture for `custom_headers` and clarifies the curl snippets. Will do a follow-up PR for the other client libs once released.
> feat: custom header fixture

- Gemfile.lock
- examples.gemspec
- style_guides/ruby/.rubocop.yml
- style_guides/ruby/easycop.yml
Rubocop v1.73 introduced a new rule we don't want to incorporate - breaks the Ruby lib PRs without this exclusion.
> fix: factory bot rule for rubocop

- official/docs/csharp/current/webhooks/create.cs
- official/docs/csharp/current/webhooks/update.cs
- official/docs/java/current/webhooks/create.java
- official/docs/java/current/webhooks/update.java
- official/docs/node/current/webhooks/create.js
- official/docs/node/current/webhooks/update.js
- official/docs/php/current/webhooks/create.php
- official/docs/php/current/webhooks/update.php
- official/docs/python/current/billing/add-stripe-bank-account.py
- official/docs/python/current/billing/add-stripe-credit-card.py
- official/docs/python/current/webhooks/create.py
- official/docs/python/current/webhooks/update.py
- official/docs/ruby/current/webhooks/create.rb
- official/docs/ruby/current/webhooks/update.rb
Fixes a couple straggling issues from new docs changeover only discovered once viewed on the webpage.
> fix: payment_method_id reference for python examples
