EasyPost/examples

community/golang/concurrent_label_buy.go
community/golang/concurrent_refund.go
community/golang/concurrent_shipment_scanform.go
community/golang/webhook_handler.go

Adds a small set of golang community examples (some I've used with customers in the past, and one non-official example that was previously stored in the golang library repo that belongs here)

chore: adds community golang examples

---

official/docs/curl/shipments/create-form.sh
official/docs/golang/shipments/create_form.go
official/docs/php/shipments/CreateForm.php

Add create form code example to missing languages

add create form code example to missing languages

---

official/fixtures/client-library-fixtures.json

Fixes casing for credit card fixture keys.

fix: credit card fixture key casing

---

.rubocop.yml
official/docs/csharp/shipments/CreateShipmentWithOptions.cs
official/docs/curl/shipments/create-shipment-with-options.sh
official/docs/go/shipments/create_shipment_with_options.go
official/docs/java/shipments/CreateShipmentWithOptions.java
official/docs/node/shipments/create_shipment_with_options.js
official/docs/php/shipments/CreateShipmentWithOptions.php
official/docs/python/shipments/create_shipment_with_options.py
official/docs/ruby/shipments/create_shipment_with_options.rb

replace shipment option from `address_validation_level ` to `print_custom_1`

replace shipment option to print_custom_1

---

official/docs/go/address/create_address.go
official/docs/go/address/verify_exisisting_address.go
official/docs/go/orders/buy_order.go
official/docs/go/reports/create_report.go
official/docs/go/reports/retrieve_list_of_reports.go

Most of the code examples are in good shape, corrected a couple of code examples.

[chore] validate Go examples

---

.eslintrc
official/docs/node/batches/add_shipments_to_batch.js
official/docs/node/batches/buy_batch.js
official/docs/node/batches/create_label.js
official/docs/node/batches/manifest_batch.js
official/docs/node/batches/remove_shipment.js
official/docs/node/carrier_accounts/delete_carrier_account.js
official/docs/node/carrier_accounts/update_carrier_account.js
official/docs/node/end_shipper/update_endshipper.js
official/docs/node/pickups/buy_pickup.js
official/docs/node/pickups/cancel_pickup.js
official/docs/node/rates/retrieve_rate.js
official/docs/node/shipments/insure_shipment.js
official/docs/node/shipments/refund_shipment.js
official/docs/node/shipments/regnerate_rates.js
official/docs/node/shipments/retrieve_smartrate.js
official/docs/node/users/update_authenticated_user.js
official/docs/node/users/update_child_user.js
official/docs/node/webhooks/update_webhook.js

Fixes various Node examples that were missing promise callbacks (especially updating objects)

fix: various Node examples missing promise callbacks

---

Makefile
official/docs/curl/billing/create-easypost-credit-card.sh
official/docs/curl/billing/create-referral-token.sh

Add two code examples in Billing
Update the Makefile for linting and installing

add two more code examples for Billing and update Makefile

---

official/tools/child_usps_carrier_account_update/README.md
official/tools/child_usps_carrier_account_update/child_accounts.csv

Adds a template to use for importing data via the child update tool

feat: adds the child_accounts.csv template file

---

official/docs/csharp/current/billing/create-ep-credit-card.cs
official/docs/csharp/v3/billing/create-ep-credit-card.cs
official/docs/golang/current/billing/create-ep-credit-card.go
official/docs/java/current/billing/create-ep-credit-card.java
official/docs/java/v5/billing/create-ep-credit-card.java
official/docs/node/current/billing/create-ep-credit-card.js
official/docs/php/current/billing/create-ep-credit-card.php
official/docs/python/current/billing/create-ep-credit-card.py
official/docs/responses/billing/billing-list.json
official/docs/ruby/current/billing/create-ep-credit-card.rb

New "Add Credit Card" example for each CL

Add "Add Credit Card" examples for each language

---

official/docs/curl/current/billing/fund.sh

Fixes a typo for the curl fund amount

fix: fund curl typo

---

official/docs/java/current/referral-customers/refund-by-payment-log.java

Another typo was caught while I am working on the API doc

fix another typo

---

official/docs/curl/current/referral-customers/add-payment-method.sh
official/docs/curl/current/referral-customers/create.sh
official/docs/curl/current/referral-customers/list.sh
official/docs/curl/current/referral-customers/refund-by-amount.sh
official/docs/curl/current/referral-customers/refund-by-payment-log.sh
official/docs/curl/current/referral-customers/update.sh

fix curl examples for referral-customers

fix curl examples for referral-customers

---

composer.json
composer.lock
go.mod
go.sum
package-lock.json
package.json
pom.xml

bump libraries version to the latest release version

bump libraries version

---

official/docs/csharp/current/events/retrieve-all-payloads.cs
official/docs/csharp/current/events/retrieve-payload.cs
official/docs/curl/current/events/retrieve-all-payloads.sh
official/docs/curl/current/events/retrieve-payload.sh
official/docs/golang/current/events/retrieve-all-payloads.go
official/docs/golang/current/events/retrieve-payload.go
official/docs/java/current/events/retrieve-all-payloads.java
official/docs/java/current/events/retrieve-payload.java
official/docs/node/current/events/retrieve-all-payloads.js
official/docs/node/current/events/retrieve-payload.js
official/docs/php/current/events/retrieve-all-payloads.php
official/docs/php/current/events/retrieve-payload.php
official/docs/python/current/events/retrieve-all-payloads.py
official/docs/python/current/events/retrieve-payload.py
official/docs/responses/events/events-retrieve-all-payloads.json
official/docs/responses/events/events-retrieve-payload.json
official/docs/ruby/current/events/retrieve-all-payloads.rb
official/docs/ruby/current/events/retrieve-payload.rb

add event payload code examples

add event payload examples

---

official/docs/curl/current/addresses/verify.sh

fix: verify curl to be a GET request

---

official/guides/ui-for-buying-shipments/step2g.erb

Remove outdated predefined package for USPS

---

official/guides/customs-guide/responses/buy-international-shipment.json
official/guides/customs-guide/responses/create-customs-info-response.json
official/guides/customs-guide/responses/create-customs-item-response.json

fix code snippet inconsistency from the code example input data

fix code snippet inconsistency

---

official/docs/responses/payloads/payloads-list.json
official/docs/responses/payloads/payloads-retrieve.json

Update our payload response examples to include more properties

Add more data to payload response examples

---

official/docs/responses/carrier-metadata/carrier-metadata-retrieve.json

Adds carrier metadata response file

feat: add carrier metadata response

---

official/docs/node/current/carrier-metadata/retrieve.js
official/docs/node/current/rates/retrieve-stateless.js
official/docs/node/current/referral-customers/add-payment-method-with-bank-account.js
official/docs/node/current/referral-customers/add-payment-method-with-credit-card.js
official/docs/node/current/referral-customers/refund-by-amount.js
official/docs/node/current/referral-customers/refund-by-payment-log.js
official/docs/node/current/referral-customers/update.js

The beta namespace was misrepresented in the examples, this PR corrects it

fix: beta namespace for node examples

---

Gemfile.lock
composer.json
composer.lock
examples.gemspec
go.mod
go.sum
official/docs/csharp/current/carrier-metadata/retrieve.cs
official/docs/curl/current/carrier-metadata/retrieve.sh
official/docs/golang/current/carrier-metadata/retrieve.go
official/docs/java/current/carrier-metadata/retrieve.java
official/docs/node/current/carrier-metadata/retrieve.js
official/docs/php/current/carrier-metadata/retrieve.php
official/docs/python/current/carrier-metadata/retrieve.py
official/docs/ruby/current/carrier-metadata/retrieve.rb
package-lock.json
package.json
pom.xml

Migrates carrier metadata examples from beta to GA

chore: change beta carrier metadata examples to GA

---

official/docs/csharp/current/rates/retrieve-stateless.cs
official/docs/golang/current/rates/retrieve-stateless.go
official/docs/java/current/rates/retrieve-stateless.java
official/docs/node/current/rates/retrieve-stateless.js
official/docs/php/current/rates/retrieve-stateless.php
official/docs/python/current/rates/retrieve-stateless.py
official/docs/ruby/current/rates/retrieve-stateless.rb

Fixes the stateless rate examples. The purpose of stateless rates is it does not create a shipment but instead, you pass in raw shipment data.

fix: stateless rate examples

---

official/docs/responses/batches/batches-create.json

Fix a typo in create batch response

fix a typo in create batch response

---

official/docs/csharp/current/child-users/list.cs
official/docs/curl/current/child-users/list.sh
official/docs/golang/current/child-users/list.go
official/docs/node/current/child-users/list.js
official/docs/php/current/child-users/list.php
official/docs/python/current/child-users/list.py
official/docs/ruby/current/child-users/list.rb

Add examples for "list child users" in all CLs + curl. 
JSON response snippet will be added via #120

[chore] Add "list child users" code examples

---

official/docs/java/current/child-users/list.java

[chore] Add missing Java code snippet

---

official/guides/create-carrier-curls/accurate.sh
official/guides/create-carrier-curls/bond.sh
official/guides/create-carrier-curls/cslogistics.sh
official/guides/create-carrier-curls/douglas.sh
official/guides/create-carrier-curls/dpdnl.sh
official/guides/create-carrier-curls/estafeta.sh
official/guides/create-carrier-curls/firstchoice.sh
official/guides/create-carrier-curls/flexport.sh
official/guides/create-carrier-curls/gio.sh
official/guides/create-carrier-curls/hailify.sh
official/guides/create-carrier-curls/henry.sh
official/guides/create-carrier-curls/hermes.sh
official/guides/create-carrier-curls/jet.sh
official/guides/create-carrier-curls/jitsu.sh
official/guides/create-carrier-curls/pandion.sh
official/guides/create-carrier-curls/speedee.sh
official/guides/create-carrier-curls/startrack.sh
official/guides/create-carrier-curls/toll.sh
official/guides/create-carrier-curls/upsmailinnovations.sh

We've added a bunch of new carriers, add the new carrier curls for each. These will soon be populated on the carrier guide pages.
Used https://github.com/Justintime50/easypost-tools/blob/main/src/tools/python/build_carrier_curl_requests.py to generate these files.

feat: add new carrier curl commands to create

---

official/guides/carriers/fedex/options.json
official/guides/carriers/usps/options.json

**why**
- required as part of our refreshed guides pages
- the snippets themselves come from support articles

add usps and fedex options

---

official/docs/curl/current/batches/buy.sh
official/docs/python/current/batches/buy.py

- **fix: curl batch buy**
- **fix: id property**

curl batch buy

---

.babelrc
Gemfile.lock
README.md
examples.gemspec
package-lock.json
package.json
style_guides/ruby/.rubocop.yml
style_guides/ruby/easycop.yml

- Fixes Ruby and Node lint configs

chore: cleanup lint config
